language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t cmuir363/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cmuir363/docker-react npm run test
